image: node:20

stages:
  - install
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test:cov
  artifacts:
    paths:
      - coverage/
    reports:
      cobertura: coverage/cobertura-coverage.xml

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
